<?php
    function str2html($str){
        $str = str_replace('&lt;', '<', $str);
        $str = str_replace('&gt;', '>', $str);
        return $str;
    }
?>
<?php
    if($comment_list['list']):
        foreach($comment_list['list'] as $comment):
?>
            <dl class="pinglun clearfix">
                <dt class="fl"><img src="<?=$comment_list['userinfo'][$comment['uid']]['url']?>" /></dt>
                <dd class="pl-hf fr">
                    <div class="pl-name clearfix">
                        <div class="name fl">
                            <a href="javascript:;"><?=$comment_list['userinfo'][$comment['uid']]['nickname']?></a>
                            <?php
                                if($comment['uid'] == $blog['userinfo']['uid']):
                            ?>
                                    <em class="lz">楼主</em>
                            <?php
                                endif;
                            ?>
                            <span><?=date('Y-m-d H:i:s', $comment['ctime'])?></span>
                        </div>
                        <!--<div class="louceng fr"><?//=$floor?>楼</div>-->
                    </div>
                    <p><?=str2html($comment['content'])?></p>
                    <?php
                    if($comment['images']):
                        foreach($comment['images'] as $image):
                            ?>
                            <img src="<?=$image['o_image']?>?imageView2/1/w/200/h/200" />
                            <?php
                        endforeach;
                    endif;
                    ?>
                    <div class="zan">
                        <a href="javascript:;" data-id="<?=$comment['id']?>" class="hf-icon fl">回复</a>
                        <a class="zan-icon action_zan" data-flag="0"><?=$comment['favor_num']?></a>
                    </div>
                    <form class="hf-form hf-formhide">
                        <textarea name="" cols="" rows="" id="content<?=$comment['id']?>_floor<?=$floor?>" placeholder="说点神马……(5~1000个字或字符)"></textarea>
                        <input type="button" value="发表" data-touid="<?=$comment['uid']?>" data-commentuid="<?=$comment['uid']?>" data-floor="<?=$floor?>" class="btn blog_reply_btn" data-flag="" />
                        <b id="face<?=$comment['id']?>_floor<?=$floor?>"></b>
                    </form>
                    <!--添加qqface-->
                    <script type="text/javascript">
                        //实例化表情插件
                        $(function(){
                            var face = '#face' + <?=$comment['id']?> + '_floor' + <?=$floor?>;
                            var content = 'content'+<?=$comment['id']?> + '_floor' + <?=$floor?>;
                            $(face).qqFace({
                                id : 'facebox1', //表情盒子的ID
                                assign: content, //给那个控件赋值
                                path:'/static/face/',	//表情存放的路径
                                tip: '/表情'
                            });
                        });
                    </script>
                    <div class="huf-box">
                        <div class="reply_list">
                    <?php
                        if($comment['reply_num'] > 0):
                            $index = 1;
                            foreach($comment['reply'] as $reply):
                                if($index >= 3){
                                    break;
                                }
                                $index++;
                    ?>
                                <div class="hf1">
                                    <span><a><?=$comment_list['userinfo'][$reply['uid']]['nickname']?></a><?=date('Y-m-d H:i:s', $reply['ctime'])?></span>
                                    <p>回复
                                    <?php
                                        if($reply['touid'] != $comment['uid']):
                                    ?>
                                            <a><?=$comment_list['userinfo'][$reply['touid']]['nickname']?></a>
                                    <?php
                                        endif;
                                    ?>
                                            : <?=str2html($reply['content'])?></p>
                                            <div class="zan">
                                                <a href="javascript:;" data-id="<?=$reply['id']?>" class="hf-icon fl">回复</a>
                                                <a class="zan-icon action_zan" data-flag="0"><?=$reply['favor_num']?></a>
                                            </div>
                                            <form class="hf-form hf-formhide">
                                                <textarea name="" cols="" rows="" id="content_reply<?=$reply['id']?>_floor<?=$floor?>" placeholder="说点神马……(5~1000个字或字符)"></textarea>
                                                <input type="button" value="发表" data-touid="<?=$reply['uid']?>" data-floor="<?=$floor?>" data-commentuid="<?=$comment['uid']?>" data-toname="<?=$comment_list['userinfo'][$reply['uid']]['nickname']?>" class="btn blog_reply_btn" data-flag="1" />
                                                <b id="face_reply<?=$reply['id']?>_floor<?=$floor?>"></b>
                                            </form>
                                            <!--添加qqface-->
                                            <script type="text/javascript">
                                                //实例化表情插件
                                                $(function(){
                                                    var face2 = '#face_reply' + <?=$reply['id']?> + '_floor' + <?=$floor?>;
                                                    var content2 = 'content_reply' + <?=$reply['id']?> + '_floor' + <?=$floor?>;
                                                    $(face2).qqFace({
                                                        id : 'facebox1', //表情盒子的ID
                                                        assign: content2, //给那个控件赋值
                                                        path:'/static/face/',	//表情存放的路径
                                                        tip: '/表情'
                                                    });
                                                });
                                            </script>
                                </div>
                    <?php
                            endforeach;
                    ?>
                        </div>
                        <?php
                            if($comment['reply_num'] > 3):
                        ?>
                                <a class="blog_comment_reply_more" data-commentuid="<?=$comment['uid']?>" data-floor="<?=$floor?>" data-id="<?=$comment['id']?>" data-page="1" style="cursor: pointer;">查看全部<?=$comment['reply_num']?>条回复</a>
                        <?php
                            endif;
                        ?>
                    <?php
                        endif;
                    ?>
                    </div>
                </dd>
            </dl>
<?php
            $floor++;
        endforeach;
    endif;
?>
<?php
    if($comment_list['list']):
?>
<script type="text/javascript">
    tmpObj.floor = tmpObj.floor + <?=count($comment_list['list'])?>;
</script>
<?php
    endif;
?>