<?php
    if(!empty($list)):
        foreach ($list as $item):
?>
    <dl class="group clearfix">
        <dt><a href="/group?g_g_id=<?=$item['g_g_id']?>"><img src="<?=$item['game_icon']?>" /></a></dt>
        <dd>
            <div class="txt">
                <a href="/group?g_g_id=<?=$item['g_g_id']?>"><?=$item['name']?></a>
                <em><?=$item['user_num']?>万成员  <?=$item['blog_num']?>帖子</em>
                <p><?=$item['summary']?></p>
            </div>
            <?php
                if($is_in_group[$item['g_g_id']] == 1):
            ?>
                <a href="javascript:;" data-is="1" data-ggid="<?=$item['g_g_id']?>" class="add yadd add-group add_group">√已加入</a>
            <?php else: ?>
                <a href="javascript:;" data-is="0" data-ggid="<?=$item['g_g_id']?>" class="add add-group add_group">加入小组</a>
            <?php
                endif;
            ?>
        </dd>
    </dl>
<?php
        endforeach;
    endif;
?>
