<script type="text/javascript" src="/static/js/userInfo.js"></script>
<div class="con-c fl">
    <table width="0" border="0" class="table">
        <tr>
            <td width="110" class="td" valign="top">输入原密码</td>
            <td><input name="oldpass" type="password" class="txt oldpass" value="" /></td>
        </tr>
        <tr>
            <td class="td" valign="top">输入新密码</td>
            <td><input name="newpass" type="password" class="txt newpass" value="" /></td>
        </tr>
        <tr>
            <td class="td" valign="top">再次输入</td>
            <td><input name="renewpass" type="password" class="txt renewpass" value="" /></td>
        </tr>
        <tr>
            <td class="td" valign="top">手机验证码</td>
            <td>
                <div class="clearfix"><input name="smscode" type="text" class="txt verify" value="" />
                    <a id="send" href="javascript:;">发送验证码</a>
                </div>
                <p class="error"></p>
            </td>
        </tr>
        <tr>
            <td class="td">&nbsp;</td>
            <td>
                <input type="button" value="保存" class="btn bs" id="save"/>
                <input type="button" value="取消" class="btn" id="reset"/>
            </td>
        </tr>
    </table>
</div>