<?php require_once(dirname(__FILE__).'/common/header.phtml'); ?>
<section class="Html-con">
    <div class="article">
        <div class="name-tx clearfix">
            <a href="javascript:;"><img src="/static/html5/images/img1.jpg" /><span>Tomoyo</span></a>
        </div>
        <h1>庆祝暗黑破坏神20周年 联动庆典即将开始</h1>
        <div class="nametime">
            <i>守望先锋小组</i>
            <em>2017-01-09</em>
        </div>
        <img src="/static/html5/images/img1.jpg" class="pic" />
        <div class="txt">
            <p>12月31日是《暗黑破坏神》20周年纪念日!</p>
            <p>我们很快将会发布2.4.3更新，为你带来一个充满乐趣的周年 活动 ，并带你重温这个经典系列的原点。在开始庆祝之前，让我们先来回顾一下我们在暗黑系列中最喜欢的时刻。</p>
            <p>有些人最喜欢的时刻是深夜狂刷巴尔，或是获得赛季最后的征服 成就 ，又或是终于刷出那把大天使之基督启示杖。还有人难以忘怀初次遭遇 屠夫 的惊吓，艰难打败督瑞尔的噩梦，或是被马萨伊尔杀死的恐惧(以及后来找他报仇)……</p>
        </div>
        <div class="share clearfix">
            <span>分享到</span>
            <a href="javascript:;"><img src="/static/html5/images/fx-qq.jpg" /></a>
            <a href="javascript:;"><img src="/static/html5/images/fx-weibo.jpg" /></a>
            <a href="javascript:;"><img src="/static/html5/images/fx-weixin.jpg" /></a>
            <a href="javascript:;"><img src="/static/html5/images/fx-kj.jpg" /></a>
        </div>
    </div>
    <!--相关阅读-->
    <div class="xg-read">
        <h3>相关阅读</h3>
        <dl class="img-txt2">
            <dd>
                <a href="javascript:;">文章标题文章标题文章标题文章标题文章标题文章标题文章标题</a>
            </dd>
        </dl>
        <dl class="img-txt2">
            <dd>
                <a href="javascript:;">文章标题文章标题文章标题文章标题文章标题文章标题文章标题</a>
            </dd>
        </dl>
        <dl class="img-txt2">
            <dd>
                <a href="javascript:;">文章标题文章标题文章标题文章标题文章标题文章标题文章标题</a>
            </dd>
        </dl>
        <dl class="img-txt2">
            <dd>
                <a href="javascript:;">文章标题文章标题文章标题文章标题文章标题文章标题文章标题</a>
            </dd>
        </dl>
    </div>
    <!--评论-->
    <div class="comment">
        <h3 class="tit clearfix">全部365条评论<a href="javascript:;">顺序查看 ↓</a><a href="javascript:;">只看楼主</a></h3>
        <dl class="pl-hf clearfix">
            <dt><a href="javascript:;"><img src="/static/html5/images/img2.jpg" /></a></dt>
            <dd>
                <div class="tit clearfix"><em>战马123</em><i>刚刚</i><b>2楼</b></div>
                <div class="pl-con">评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容评论内容</div>
                <div class="zan-box">
                    <a href="javascript:;" class="zan">6</a>
                    <a href="javascript:;" class="hf">回复</a>
                </div>
                <form class="hf-form">
                    <textarea name="" cols="" rows="" id="content1">说点神马……</textarea>
                    <div class="fb-btn clearfix">
                        <input type="button" value="发表" class="btn" />
                    </div>
                </form>
            </dd>
        </dl>
        <dl class="pl-hf clearfix">
            <dt></dt>
            <dd>
                <div class="tit"><em>用户名称1</em><i>2017-01-09 13:07</i></div>
                <div class="pl-con">这是回复的内容回复的内容回复的</div>
                <div class="zan-box">
                    <a href="javascript:;" class="zan">6</a>
                    <a href="javascript:;" class="hf">回复</a>
                </div>
                <form class="hf-form">
                    <textarea name="" cols="" rows="" id="content1">说点神马……</textarea>
                    <div class="fb-btn clearfix">
                        <input type="button" value="发表" class="btn" />
                    </div>
                </form>
            </dd>
        </dl>
        <dl class="pl-hf clearfix">
            <dt></dt>
            <dd>
                <div class="tit"><em>用户名称2</em><i>2017-01-09 13:07</i></div>
                <div class="pl-con">回复用户昵称1：这是回复的内容回复的内容回</div>
                <div class="zan-box">
                    <a href="javascript:;" class="zan">6</a>
                    <a href="javascript:;" class="hf">回复</a>
                </div>
                <form class="hf-form">
                    <textarea name="" cols="" rows="" id="content1">说点神马……</textarea>
                    <div class="fb-btn clearfix">
                        <input type="button" value="发表" class="btn" />
                    </div>
                </form>
            </dd>
        </dl>
        <dl class="pl-hf nonCritical clearfix">
            <dt></dt>
            <dd>
                <div class="tit"><em>用户名称2</em><i>2017-01-09 13:07</i></div>
                <div class="pl-con">回复用户昵称1：这是回复的内容回复的内容回</div>
                <div class="zan-box">
                    <a href="javascript:;" class="zan">6</a>
                    <a href="javascript:;" class="hf">回复</a>
                </div>
                <form class="hf-form">
                    <textarea name="" cols="" rows="" id="content1">说点神马……</textarea>
                    <div class="fb-btn clearfix">
                        <input type="button" value="发表" class="btn" />
                    </div>
                </form>
            </dd>
        </dl>
        <dl class="pl-hf nonCritical clearfix">
            <dt></dt>
            <dd>
                <div class="tit"><em>用户名称2</em><i>2017-01-09 13:07</i></div>
                <div class="pl-con">回复用户昵称1：这是回复的内容回复的内容回</div>
                <div class="zan-box">
                    <a href="javascript:;" class="zan">6</a>
                    <a href="javascript:;" class="hf">回复</a>
                </div>
                <form class="hf-form">
                    <textarea name="" cols="" rows="" id="content1">说点神马……</textarea>
                    <div class="fb-btn clearfix">
                        <input type="button" value="发表" class="btn" />
                    </div>
                </form>
            </dd>
        </dl>
        <div class="control"><a href="javascript:;" class="look-more">查看全部2条回复</a></div>
    </div>
</section>

<script type="text/javascript">
    $('.hf').click(function(){
        //alert('a')
        $(this).parent('.zan-box').next('.hf-form').show();
    });
    $(".nonCritical").hide();
    // 筛选面板“更多”和“收起”的功能
    $(".control").delegate('a.look-more','click',function(){
        $(".nonCritical").show();
        $(this).hide().next().show();
    })
</script>
<?php require_once(dirname(__FILE__).'/common/footer.phtml'); ?>