<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>帖子详情</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">
    <link href="/static/html5/css/master.css" type="text/css" rel="stylesheet" />
    <script src="/static/html5/js/jquery-1.9.1.min.js"></script>
</head>


<body>
<!--头部-->
<header class="header clear">
    <h1><a href="javascript:;"><img src="/static/html5/images/logo.png" /><span>红点游戏</span></a></h1>
    <a href="javascript:;">下载APP</a>
</header>
