<?php require_once(dirname(__FILE__).'/header.phtml'); ?>

<div class="Html-con con1 clearfix">
	<!--左-->
	<div class="con-l-878 fl">
    	<div class="pages-top">
        	<a href="/">首页</a> >
			<a href="/index/game?type=<?=$article['channel']?>"><?=$list_type[$article['channel']]['name']?></a> >
            <span>正文</span>
        </div>
        <div class="article">
        	<div class="article-tit">
            	<h1><?=htmlspecialchars($article['title'])?></h1>
                <div class="name-time">
                	<em><?=htmlspecialchars($article['author'])?></em>
                    <em><?=$article['time_str']?></em>
                </div>
            </div>
            <div class="article-txt">
            	<?=urldecode($article['content'])?>
            </div>
            <div class="article-box1 clearfix">
            	<div class="wenzi fl">
                    <?php
                    $tagArr = $article['tags'];
                    if(is_array($tagArr) && !empty($tagArr)){
                        foreach ($tagArr as $tag) {
                            if(empty($tag)) echo '<em>'.htmlspecialchars($tag).'</em>';
                        }
                    }
                    ?>
                </div>
                <div class="read fr">
                	<a href="<?=$article['url']?>" target="_blank">阅读原文</a>
                    <a id="report" href="javascript:;" data-aid="<?=$article['aid']?>">举报</a>
                </div>
            </div>
            <div id="share" class="share clearfix" data-url="<?=$cururl?>" data-title="<?=$article['title']?>" data-desc="<?=$article['desc']?>" data-image="">
            	<span>分享到</span>
                <a href="javascript:;" class="icon5 qq"></a>
                <a href="javascript:;" class="icon6 wb"></a>
                <a href="javascript:;" class="icon7 wx"></a>
                <a href="javascript:;" class="icon8 qqzone"></a>
            </div>
            <!--评论-->
            <div class="all-comment">
            	<h3>全部<b><?=$article['comment_num']?></b>条评论</h3>
                <div class="pinglun-input clearfix">
                    <?php if($isLogin){ ?>
                	<div class="img"><img src="<?=$self['url']?>" /></div>
                    <?php } ?>
                    <form id="f_comment">
                        <input name="aid" type="hidden" value="<?=$article['aid']?>" />
                        <textarea id="txt" name="content" class="txt" placeholder="说点神马……"></textarea>
                    	<input id="f_submit" type="button" class="btn" value="评论" />
                    </form>
                </div>
                <dl class="pinglun clearfix" data-aid="<?=$article['aid']?>" data-page="1" data-pagecount="<?=$comment['pageCount']?>">
                <?php require(dirname(__FILE__).'/common/article_comment_list.phtml'); ?>
                </dl>
            </div>
        </div>
    </div>
    <!--右-->
	<div class="con-r fr">
    	<div class="box4-dl tpl_morepic">
    		<h3>相关阅读</h3>
            <?php
            $relateArticleArr = isset($relate['articles']) ? $relate['articles'] : [];
            $relateAdsArr = isset($relate['ads']) ? $relate['ads'] : [];
            if(is_array($relateArticleArr) && !empty($relateArticleArr)){
                $adoffset = rand(1,count($relateArticleArr));
                foreach ($relateArticleArr as $key => $value) {
                    echo '<dl class="clearfix">';
                    if(!empty($value['images'][0]['z_image'])){
                        echo '<dt class="fl"><img src="'.$value['images'][0]['z_image'].'" /></dt>';
                    }
                    echo '<dd class="fl"><a href="/article/index?aid='.$value['aid'].'">'.htmlspecialchars($value['title']).'</a></dd>';
                    echo '</dl>';
                    if(!empty($relateAdsArr) && $key == $adoffset){
                        echo '<dl class="clearfix">';
                        if(!empty($relateAdsArr['url'])){
                            echo '<dt class="fl"><img src="'.$relateAdsArr['url'].'" /></dt>';
                        }
                        echo '<dd class="fl"><a href="'.$relateAdsArr['ad_url'].'">'.htmlspecialchars($value['title']).'</a></dd>';
                        echo '</dl>';
                    }
                }
            }
            ?>
        </div>
        <div class="box4 tpl_video">
            <!--<h3>热门视频</h3>
            <?php
            if(is_array($hotVideo) && !empty($hotVideo)){
                foreach ($hotVideo as $video) {
                    echo '<dl>';
                    if(!empty($video['image'])){
                        echo '<dt><img src="'.$video['image'].'" /></dt>';
                    }
                    echo '<dd>'.htmlspecialchars($video['title']).'</dd>';
                    echo '</dl>';
                }
            }
            ?> -->
        </div>
    </div>
</div>
<script src="/static/js/article.js" type="text/javascript"></script>
<?php require_once(dirname(__FILE__).'/footer.phtml'); ?>