<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baidu-site-verification" content="aVyIudH8OW" />
<meta name="keywords" content="红点游戏，游戏，游戏社区，游戏资讯，红点游戏官网" />
<meta name="description" content="《红点游戏》(www.hongdiangame.com)是由北京宙客科技有限公司研发的游戏社交产品。红点游戏是基于数据挖掘，以用户兴趣为导向，实现个性化推荐的推荐引擎，也是记录用户游戏生活，分享游戏体验的游戏社区。" />
    <title><?=$head_title?></title>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/static/css/common.css" />
<script src="/static/js/jquery-1.3.2.js" type="text/javascript"></script>
<script src="/static/js/jquery.md5.js" type="text/javascript"></script>
<script src="/static/js/public.js" type="text/javascript"></script>
</head>
<body>
<!--登录弹框-->
<div class="tan"></div>
<div class="tan-con tan-login">
	<div class="tan-tit">
    	<h3>登录</h3>
        <b class="close"></b>
    </div>
    <div class="login">
        <div class="txt-box clearfix">
            <div class="tablebox" id="menu">
                <div class="tablebox1">+86</div>
                <!-- <ul  class="tablebox2">
                    <li>+886</li>
                    <li>+852</li>
                    <li>+60</li>
                </ul> -->
            </div>
            <input id="login_phone" name="login_phone" type="text" class="txt" placeholder="请输入手机号" />
        </div>
        <div class="txt-box clearfix">
            <div class="tit">密码</div>
            <input id="login_password" name="login_password" type="password" class="txt" placeholder="请输入密码" />
        </div>
        <input type="button" value="登录" onclick="sso.dologin()" class="btn" />
        <div class="zhuce">
        	<span><a href="javascript:;" class="zhuce-a" onclick="sso.regist()">注册账号</a>/</span>
           	<span><a href="javascript:;" onclick="sso.verify()">忘记密码</a></span>
        </div>
        <span id="login_err" class="no-existence"></span>
    </div> 
    <div class="other-login">
    	<!-- <h3>其他登录</h3>
    	<span>
        	<a href="javascript:;"><img src="/static/images/weibo.jpg" /><em>微博</em></a>             
        </span>
        <span>
        	<a href="javascript:;"><img src="/static/images/weixin.jpg" /><em>微信</em></a>             
        </span>
        <span>
        	<a href="javascript:;"><img src="/static/images/qq.jpg" /><em>QQ</em></a>             
        </span> -->
    </div>       
</div>

<div class="tan-con tan-regist">
	<div class="tan-tit">
    	<h3>新用户注册</h3>
        <b class="close"></b>
    </div>
    <div class="login">
    	<div class="txt-box clearfix">
            <div class="tit">昵称</div>
            <input id="regist_nickname" name="regist_nickname" type="text" class="txt" placeholder="请输入汉字、英文或数字的组合" />
        </div>
        <div class="txt-box clearfix">
            <div class="tablebox" id="menu">
                <div class="tablebox1">+86</div>
                <!-- <ul  class="tablebox2">
                    <li>+86</li>
                    <li>+852</li>
                    <li>+60</li>
                </ul> -->
            </div>
            <input id="regist_phone" name="regist_phone" type="text" class="txt" placeholder="请输入手机号" />
        </div>
        <div class="txt-box clearfix">
            <div class="tit">密码</div>
            <input id="regist_password" name="regist_password" type="password" class="txt" placeholder="6~20个英文+数字，区分大小写" />
        </div>
        <span id="regist_err" class="no-existence"></span>
    </div>
    <div class="btn-botton">
    	<p>注册即表示同意红点游戏<a href="javascript:;">注册协议</a></p>
        <input type="button" value="注册" onclick="sso.doregist()" class="btn" />
    </div>
</div>

<div class="tan-con tan-activate">
	<div class="tan-tit">
    	<h3>激活账号</h3>
        <b class="close"></b>
    </div>
    <div class="login">
    	<div class="txt-box clearfix">
            <div class="tit">手机验证</div>
            <input id="activate_code" name="activate_code" type="hidden" value=""  />
            <input id="activate_phone" name="activate_phone" type="hidden" value=""  />
            <input id="activate_uid" name="activate_uid" type="hidden" value=""  />
            <input id="activate_smscode" name="activate_smscode" type="text" class="txt" placeholder="请输入验证码" />
        </div>
        <p>验证码已发送短信，请在30分钟内输入</p>
        <a href="javascript:;" class="yzm-btn" onclick="sso.dosms('activate')" data-cando="1"><i></i>重新发送</a>
        <span id="activate_err" class="no-existence"></span>
    </div>
    <div class="btn-botton">
        <input type="button" value="完成" onclick="sso.doactivate()" class="btn close" />
    </div>
</div>

<div class="tan-con tan-verify">
    <div class="tan-tit">
        <h3>验证账号</h3>
        <b class="close"></b>
    </div>
    <div class="login">
        <div class="txt-box clearfix">
            <div class="tablebox" id="menu">
                <div class="tablebox1">+86</div>
                <!-- <ul  class="tablebox2">
                    <li>+86</li>
                    <li>+852</li>
                    <li>+60</li>
                </ul> -->
            </div>
            <input id="verify_phone" name="verify_phone" type="text" class="txt" placeholder="请输入手机号" />
        </div>
        <span id="verify_err" class="no-existence"></span>
    </div>
    <div class="btn-botton">
        <input type="button" value="验证账号" onclick="sso.doverify()" class="btn" />
    </div>
</div>

<div class="tan-con tan-modify">
    <div class="tan-tit">
        <h3>重置密码</h3>
        <b class="close"></b>
    </div>
    <div class="login">
        <div class="txt-box clearfix">
            <div class="tit">密码</div>
            <input id="modify_password" name="modify_password" type="password" class="txt" placeholder="6~20个英文+数字，区分大小写" />
        </div>
        <div class="txt-box clearfix">
            <div class="tit">验证码</div>
            <input id="modify_code" name="modify_code" type="hidden" value=""  />
            <input id="modify_phone" name="modify_phone" type="hidden" value=""  />
            <input id="modify_uid" name="modify_uid" type="hidden" value=""  />
            <input id="modify_smscode" name="modify_smscode" type="text" class="txt" placeholder="请输入验证码" />
        </div>
        <p>验证码已发送短信，请在30分钟内输入</p>
        <a href="javascript:;" class="yzm-btn" onclick="sso.dosms('modify')" data-cando="1"><i></i>重新发送</a>
        <span id="modfiy_err" class="no-existence"></span>
    </div>
    <div class="btn-botton">
        <input type="button" value="重置密码" onclick="sso.domodify()" class="btn close" />
    </div>
</div>

<div class="tan-con tan-popup">
    <div class="tan-tit">
        <h3></h3>
        <b class="close"></b>
    </div>
    <div class="tan-txt">
        <p></p>
    </div>
</div>

<div class="header">
	<div class="Html-con clearfix">
    	<!--logo-->
    	<h1 class="fl"><a href="/"><img src="/static/images/logo.jpg" /></a></h1>
        <!--搜索框-->
        <div class="search fl">
        	<form class="form" onsubmit="return false;">
            	<input type="text" placeholder="大家都在搜：后街男孩创始人去世" class="txt keywords" value="<?php if($keywords){echo $keywords;}?>" />
                <ul class="search-list">
                	<!--<li>搜索联想词1</li>
                    <li>搜索联想词2</li>
                    <li>搜索联想词3</li>
                    <li>搜索联想词4</li>
                    <li>搜索联想词5</li>
                    <li>搜索联想词6</li>
                    <li>搜索联想词7</li>
                    <li>搜索联想词8</li>-->
                </ul>
                <input type="button" class="but" />
            </form>
        </div>
        <div class="header-right fr">
            <?php if($isLogin){ ?>
            <a href="/user/profile" class="login"><img src="<?=$self['url']?>" width="30" height="30" class="head_picture"/>&nbsp;&nbsp;<?=htmlentities($self['nickname'])?></a>
			<a href="javascript:;" onclick="sso.logout()" class="login">&nbsp;|&nbsp;退出</a>
            <a href="/user/userinfo"><b class="icon2"></b></a>
            <a href="/user/message" id="header_msg_num"><b class="icon1"></b></a>
            <?php }else{ ?>
        	<a href="javascript:;" class="login" onclick="sso.login()"><b></b>登录</a>
            <!-- <a href="javascript:;"><b class="icon2"></b></a>
            <a href="javascript:;"><b class="icon1"></b></a> -->
            <?php } ?>
        </div>
    </div>
</div>